- dimensionality: [80]
  max_training_timesteps: [2_000]
  lambdas: [[1, 2, 4, 8, 16, 32]]
  num_environments: [16]
  num_evaluation_episodes: [150]
  num_timesteps_per_evaluation: [400]
  ppo:
    batch_size: [64]
    device: [auto]
    clip_range: [0.2]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [0.99]
    learning_rate: [0.0003]
    n_epochs: [10]
    n_steps: [2_048]
    net_arch: [[50, 50]]
    policy: [MlpPolicy]
    vf_coef: [0.5]
    max_grad_norm: [0.5]
    sde_sample_freq: [-1]
    stats_window_size: [100]
    verbose: [0]
  slurm:
    account: [ec262-dimitri]
    cpus_per_task: [1]
    nodes: [1]
    partition: [standard]
    qos: [standard]
    ntasks_per_node: [1]
    time: ["07:00:00"]
  closeness_to_optimum: [0.5]
  random_seed: "list(range(100, 110))"
  reward_type: [EVALUATIONS_PLUS_FITNESS]
  state_type: [ONE_HOT_ENCODED]
