- dimensionality: [100]
  lambdas: [[1, 2, 4, 8, 16, 32]]
  max_training_timesteps: [2_000_000]
  num_environments: [1]
  num_evaluation_episodes: [500]
  num_timesteps_per_evaluation: [2_048]
  ppo:
    batch_size: [64]
    clip_range: [0.2]
    device: [auto]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [0.99]
    learning_rate: [0.0003]
    max_grad_norm: [0.5]
    n_epochs: [10]
    n_steps: [2_048]
    policy: [MlpPolicy]
    sde_sample_freq: [-1]
    stats_window_size: [100]
    verbose: [0]
    vf_coef: [0.5]
  slurm:
    account: [ec262-dimitri]
    cpus_per_task: [1]
    nodes: [1]
    ntasks_per_node: [1]
    partition: [standard]
    qos: [standard]
    time: ["10:45:00"]
  closeness_to_optimum: [0.5, 0.85]
  random_seed: "list(range(100, 103))"
  reward_type: [EVALUATIONS_PLUS_FITNESS]
  state_type: [ONE_HOT_ENCODED]

- dimensionality: [200]
  lambdas: [[1, 2, 4, 8, 16, 32, 64]]
  max_training_timesteps: [2_000_000]
  num_environments: [1]
  num_evaluation_episodes: [500]
  num_timesteps_per_evaluation: [2_048]
  ppo:
    batch_size: [64]
    clip_range: [0.2]
    device: [auto]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [0.99]
    learning_rate: [0.0003]
    max_grad_norm: [0.5]
    n_epochs: [10]
    n_steps: [2_048]
    policy: [MlpPolicy]
    sde_sample_freq: [-1]
    stats_window_size: [100]
    verbose: [0]
    vf_coef: [0.5]
  slurm:
    account: [ec262-dimitri]
    cpus_per_task: [1]
    nodes: [1]
    ntasks_per_node: [1]
    partition: [standard]
    qos: [standard]
    time: ["10:45:00"]
  closeness_to_optimum: [0.5]
  random_seed: "list(range(100, 103))"
  reward_type: [EVALUATIONS_PLUS_FITNESS]
  state_type: [ONE_HOT_ENCODED]

- dimensionality: [500]
  lambdas: [[1, 2, 4, 8, 16, 32, 64, 128]]
  max_training_timesteps: [2_000_000]
  num_environments: [1]
  num_evaluation_episodes: [500]
  num_timesteps_per_evaluation: [2_048]
  ppo:
    batch_size: [64]
    clip_range: [0.2]
    device: [auto]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [0.99]
    learning_rate: [0.0003]
    max_grad_norm: [0.5]
    n_epochs: [10]
    n_steps: [2_048]
    policy: [MlpPolicy]
    sde_sample_freq: [-1]
    stats_window_size: [100]
    verbose: [0]
    vf_coef: [0.5]
  slurm:
    account: [ec262-dimitri]
    cpus_per_task: [1]
    nodes: [1]
    ntasks_per_node: [1]
    partition: [standard]
    qos: [standard]
    time: ["10:45:00"]
  closeness_to_optimum: [0.5]
  random_seed: "list(range(100, 103))"
  reward_type: [EVALUATIONS_PLUS_FITNESS]
  state_type: [ONE_HOT_ENCODED]
