dependencies:
  - python=3.10
  - pip=23.3
  - pip:
    - /home/dimitri/code/DACBench
    - colored==2.2.3
    - gymnasium==0.29.1
    - jupyter==1.0.0
    - numpy==1.24.2
    - plotly==5.18.0
    - scikit-learn==1.2.2
    - seaborn==0.12.2
