#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

# Customizing the PS4 variable to show expanded variables
export PS4='+ \e[36m${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }$ \e[m'

# Enable debugging if the last argument is --verbose
if [[ "${@: -1}" == "--verbose" ]]; then
  set -x
  set -- "${@:1:$(($#-1))}"  # Remove the last argument (--verbose)
fi

if [ "$(whoami)" = "dimitri_rusin_cirrus" ]; then
  module load anaconda3/2023.09
  cd /work/ec262/ec262/dimitri_rusin_cirrus/oll_onemax
fi

# Initialize and update git submodules
if [ -d .git ]; then
  # Rename remote from origin to github [Having a remote named origin has caused an issue in the past.]
  git submodule | awk '{ print $2 }' | while read -r submodule_path; do
    if git -C "$submodule_path" remote | grep -qx 'origin'; then
      git -C "$submodule_path" remote rename origin github
    fi
  done
  git submodule init
  git submodule update
fi

# Define the directory for local Miniconda installation
MINICONDA_DIR=".deploy/Miniconda3/"

# Clean up any previous Conda environment and build targets
rm -rf $MINICONDA_DIR

# Install Miniconda locally
curl -o /tmp/Miniconda3.sh https://repo.anaconda.com/miniconda/Miniconda3-py39_24.5.0-0-Linux-x86_64.sh
bash /tmp/Miniconda3.sh -b -p $MINICONDA_DIR
rm /tmp/Miniconda3.sh

# Initialize conda in the current shell (without modifying any shell configuration files)
eval "$(.deploy/Miniconda3/bin/conda shell.bash hook)"

# Activate the base Conda environment
conda activate base

# Clean up any previous Conda environment and build targets
rm -rf .deploy/conda_environment/

# Create and activate a new Conda environment based on .conda.yaml configuration
conda env create --prefix .deploy/conda_environment/ --file .deploy/conda.yaml --debug
conda activate .deploy/conda_environment/

# Install Python dependencies from the requirements file
pip install --requirement .deploy/pip.txt
