#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

# Customizing the PS4 variable to show expanded variables
export PS4='+ \e[36m${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }$ \e[m'

# Enable debugging if the last argument is --verbose
if [[ "${@: -1}" == "--verbose" ]]; then
  set -x
  set -- "${@:1:$(($#-1))}"  # Remove the last argument (--verbose)
fi

if [ "$(whoami)" = "dimitri_rusin_cirrus" ]; then
  module load anaconda3/2023.09
  cd /work/ec262/ec262/dimitri_rusin_cirrus/oll_onemax
fi

# Initialize and update git submodules
if [ -d .git ]; then
  # Rename remote from origin to github [Having a remote named origin has caused an issue in the past.]
  git submodule | awk '{ print $2 }' | while read -r submodule_path; do
    if git -C "$submodule_path" remote | grep -qx 'origin'; then
      git -C "$submodule_path" remote rename origin github
    fi
  done
  git submodule init
  git submodule update
fi

# Initialize conda in the current shell (without modifying any shell configuration files)
eval "$(.deploy/miniconda/bin/conda shell.bash hook)"

# The set envelopment comes from an issue where the Anaconda3 access unset variables. We disable our shell policy (set above) of stopping
# script execution, when an unset variable is accessed. More info: https://github.com/conda/conda/issues/3200
set +u
conda activate .deploy/conda_environment/
set -u

# Check if Cargo is installed. If not install Cargo. Then install maturin.
if ! command -v $HOME/.cargo/bin/cargo &> /dev/null
then
  echo "Cargo is not installed. Installing Cargo..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  source "$HOME/.cargo/env"
fi

$HOME/.cargo/bin/cargo install maturin --version 1.5.1

rm -rf DE0CH_OLL/onell_algs_rs/target/

# Build Rust project using maturin, within its directory (isolated in a subshell)
(
  cd DE0CH_OLL/onell_algs_rs/
  rm -rf target/
  maturin build --release
)

# Find and install the Python wheel files built by maturin
find DE0CH_OLL/onell_algs_rs/target/wheels -name "*.whl" -print0 | xargs -0 pip install --force-reinstall
