#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

# Customizing the PS4 variable to show expanded variables
export PS4='+ \e[36m${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }$ \e[m'

# Enable debugging if the last argument is --verbose
if [[ "${@: -1}" == "--verbose" ]]; then
  set -x
  set -- "${@:1:$(($#-1))}"  # Remove the last argument (--verbose)
fi

if [ "$(whoami)" = "dimitri_rusin" ]; then
  module load anaconda3/2023.09
  cd /work/sc122/sc122/dimitri_rusin/oll_onemax/
fi

# Find the path to the conda executable
conda_path=$(which conda)

# Determine the path to conda.sh based on the conda executable location
if [[ "$conda_path" == */condabin/conda ]]; then
  conda_sh_path="${conda_path%/condabin/conda}/etc/profile.d/conda.sh"
elif [[ "$conda_path" == */bin/conda ]]; then
  conda_sh_path="${conda_path%/bin/conda}/etc/profile.d/conda.sh"
else
  echo "Error: Unable to locate the conda.sh file."
  exit 1
fi

# Source conda.sh if it exists, else export PATH
if [ -f "$conda_sh_path" ]; then
  echo "Sourcing: $conda_sh_path"
  source "$conda_sh_path"
else
  echo "Exporting PATH with Conda bin directory"
  export PATH="${conda_path%/bin/conda}/bin:$PATH"
fi



# Initialize and update git submodules
git submodule init
git submodule update

# Activate the base Conda environment
conda activate base

# Clean up any previous Conda environment and build targets
rm -rf .deploy/conda_environment/
rm -rf DE0CH_OLL/onell_algs_rs/target/

# Create and activate a new Conda environment based on .conda.yaml configuration
conda env create --prefix .deploy/conda_environment/ --file .deploy/conda.yaml --debug
conda activate .deploy/conda_environment/

# Install Python dependencies from the requirements file
pip install --requirement .deploy/pip.txt
