- action_type: [DISCRETE]
  db_path: ["computed/{hostname}/num_environments/{wordhash}.db"]
  dimensionality: [80]
  max_training_timesteps: [500_000]
  mutation_sizes: [[5, 6, 7, 8]]
  crossover_sizes: [[5, 6, 7, 8]]
  num_environments: [4, 8, 16]
  num_evaluation_episodes: [1_000]
  num_timesteps_per_evaluation: [4_000]
  num_timesteps_with_teacher: [0]
  ppo:
    batch_size: [100]
    clip_range: [0.2]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [1]
    learning_rate: [0.0003]
    n_epochs: [10]
    n_steps: [2_000]
    net_arch: [[50, 50]]
    policy: [MlpPolicy]
    vf_coef: [0.5]
  slurm:
    account: [sc122-dimitri]
    cpus_per_task: [1]
    nodes: [1]
    partition: [standard]
    qos: [standard]
    ntasks_per_node: [1]
    time: ["04:00:00"]
  probability_of_closeness_to_optimum: [0.95, 0.8]
  random_seed: [42]
  reward_type: [EVALUATIONS_PLUS_FITNESS]
  state_type: [ONE_HOT_ENCODED]
