- action_type: [DISCRETE, CONTINUOUS]
  db_path: ["computed/{hostname}/continuous/{wordhash}.db"]
  max_training_timesteps: [500_000]
  n: [80]
  num_evaluation_episodes: [1_000]
  num_lambdas: [8]
  num_timesteps_per_evaluation: [4_000]
  ppo:
    batch_size: [100]
    clip_range: [0.2]
    ent_coef: [0.0]
    gae_lambda: [0.95]
    gamma: [1]
    learning_rate: [0.0003]
    n_epochs: [10]
    n_steps: [2_000]
    net_arch: [[50, 50]]
    policy: [MlpPolicy]
    vf_coef: [0.5]
  probability_of_closeness_to_optimum: [0.95]
  random_seed: [42, 83, 2]
  reward_type: [ONLY_EVALUATIONS, EVALUATIONS_PLUS_FITNESS]
  state_type: [SCALAR_ENCODED, ONE_HOT_ENCODED]
