#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail



# Dynamically find the Conda executable path
conda_path=$(which conda)

# Determine the correct path for conda.sh based on the location of the conda executable
if [[ "$conda_path" == */condabin/conda ]]; then
  conda_sh_path="${conda_path%/condabin/conda}/etc/profile.d/conda.sh"
elif [[ "$conda_path" == */bin/conda ]]; then
  conda_sh_path="${conda_path%/bin/conda}/etc/profile.d/conda.sh"
else
  echo "Error: Unable to locate the conda.sh file."
  exit 1
fi

echo "Sourcing: $conda_sh_path"
# Source the conda.sh script for proper initialization
source "$conda_sh_path"



conda activate .deploy/conda_environment
source <(python .deploy/apply.py config/dim_50.yaml)
python src/generate.py
