#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

# Customizing the PS4 variable to show expanded variables
export PS4='+ \e[36m${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }$ \e[m'

# Enable debugging if the last argument is --verbose
if [[ "${@: -1}" == "--verbose" ]]; then
  set -x
  set -- "${@:1:$(($#-1))}"  # Remove the last argument (--verbose)
fi

if [ "$(whoami)" = "dimitri_rusin_cirrus" ]; then
  module load anaconda3/2023.09
  cd /work/ec262/ec262/dimitri_rusin_cirrus/oll_onemax
fi

# Find the path to the conda executable
conda_path=$(which conda)

# Determine the path to conda.sh based on the conda executable location
if [[ "$conda_path" == */condabin/conda ]]; then
  conda_sh_path="${conda_path%/condabin/conda}/etc/profile.d/conda.sh"
elif [[ "$conda_path" == */bin/conda ]]; then
  conda_sh_path="${conda_path%/bin/conda}/etc/profile.d/conda.sh"
else
  echo "Error: Unable to locate the conda.sh file."
  exit 1
fi

# Source conda.sh if it exists, else export PATH
if [ -f "$conda_sh_path" ]; then
  echo "Sourcing: $conda_sh_path"
  source "$conda_sh_path"
else
  echo "Exporting PATH with Conda bin directory"
  export PATH="${conda_path%/bin/conda}/bin:$PATH"
fi

# Check for the YAML file path argument
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <yaml_path>"
  exit 1
fi

yaml_path="$1"

# The set envelopment comes from an issue where the Anaconda3 access unset variables. We disable the shell policy to stop
# script execution, when an unset variable is accessed. More info: https://github.com/conda/conda/issues/3200
set +u
conda activate .deploy/conda_environment
set -u

# Generate a temporary file in /tmp
temp_env_file=$(mktemp /tmp/env.XXXXXX)

# Generate the environment variables and capture them in the temporary file
python config/apply.py "$yaml_path" > "$temp_env_file"

# Check if the previous command was successful
if [ $? -ne 0 ]; then
  echo "Error occurred in apply.py"
  rm -f "$temp_env_file"
  exit 1
fi

# Source the environment variables if the Python script was successful
source "$temp_env_file"
rm -f "$temp_env_file"

# Export OO__SLURM_JOB_ID with SLURM_JOB_ID value if set
[[ -n ${SLURM_JOB_ID:-} ]] && export OO__SLURM_JOB_ID=$SLURM_JOB_ID

# Continue with the rest of the script
python src/generate.py
