#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

# Customizing the PS4 variable to show expanded variables
export PS4='+ \e[36m${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }$ \e[m'

# Enable debugging if the last argument is --verbose
if [[ "${@: -1}" == "--verbose" ]]; then
  set -x
  set -- "${@:1:$(($#-1))}"  # Remove the last argument (--verbose)
fi

if [ "$(whoami)" = "dimitri_rusin_cirrus" ]; then
  module load anaconda3/2023.09
  cd /work/ec262/ec262/dimitri_rusin_cirrus/oll_onemax
fi

eval "$(.deploy/miniconda/bin/conda shell.bash hook)"

conda activate .deploy/conda_environment

python config/config.py "$1"
