db_path: computed/data/dim_500.db
episodes: 999_999_999_999
epsilon: 0.1
evaluation_interval: 10
gamma: 1
learning_rate: 0.1
n: 500
num_evaluation_episodes: 200
num_training_timesteps: 1_000_000
probability_of_closeness_to_optimum: 0.9
random_seed: 42
