random_seed: 42
db_path: computed/data/dim_50.db
episodes: 999_999_999_999
num_training_timesteps: 1_000_000
epsilon: 0.1
evaluation_interval: 100
gamma: 1
learning_rate: 0.1
n: 50
num_evaluation_episodes: 200

execution:
  episode_id_low: 3
  episode_id_high: 300
  folder_path: data/executions/
